### ISSUE TITLE
non-static method uploadImage(Part) cannot be referenced from a static context

### ISSUE THREAD

**Issue by Isabellle** [pratikbutani/RetrofitImageUpload#1]
I'm trying to implement your solution. First of all; thanks, the code is really awesome.
But I'm getting the following error:
`Error:(132, 53) error: non-static method uploadImage(Part) cannot be referenced from a static context`

It happens at this line:
`Call<Result> resultCall = ImageUploadService.uploadImage(body);`

I took the same code as yours:
`public interface ImageUploadService {
    @Multipart
    @POST("upload.php")
    Call<Result> uploadImage(@Part MultipartBody.Part file);
}`

Do you have any idea of what I've doing wrong?

Thanks a lot,

**Comment by Isabellle** [comment]
My fault! I was calling ImageUploadService instead of imageUploadService.

**Comment by pratikbutani** [comment]
Hello, Thanks for your appreciation.

Its not working static because `ImageUploadService` is not class and inside that `uploadImage` is not static method.

So you must have to create object of that like:

```
//Create Upload Server Client
ApiService service = RetroClient.getApiService();
```

Hope you will get it.

Thank you. Keep staring :) :+1:

**Comment by Isabellle** [comment]
That was it! Thanks again.
