### ISSUE TITLE
how can i upload file instead of image !

### ISSUE THREAD

**Issue by deshario** [pratikbutani/RetrofitImageUpload#2]
How can i upload file instead of image ... for example i wanna upload some .db files into server !
What files should i modify! It will be very helpful to me Thankx ....

**Comment by pratikbutani** [comment]
You can use this one : [Upload file to Server using Retrofit 2](https://futurestud.io/tutorials/retrofit-2-how-to-upload-files-to-server)

**Comment by deshario** [comment]
how can we use php as backend in this code ? 
Can we use php instead of Hapi
