### ISSUE TITLE
how can i run this demo?

### ISSUE THREAD

**Issue by WigginsW** [pratikbutani/RetrofitImageUpload#4]
I have a question. I clone this demo in my pc and install it . But i cann't  upload image. When i selected photo, then will show a progress which said "Uploading.. Wait for a while...". So i try debug this demo, i find this is nothing happened  after progress.

**Comment by pratikbutani** [comment]
I think you have not done things following thing::
- Have you put `php_upload` folder in `htdocs` folder
- Have you configure IP Address in URL while calling from android. See [RetrofitClient.java](https://github.com/pratikbutani/RetrofitImageUpload/blob/master/app/src/main/java/com/androidbuts/api/RetroClient.java#L17)

OR 

Let me know what types of error did you get in LOG.

**Comment by WigginsW** [comment]
I'm so sorry to reply you now. I found a another way to upload image on my application.  And i will try you told to me. I ’m glad you replay me. Thank you!
